   - name: Installng Java 1.7.0
     yum: name=java-1.7.0-openjdk state=present

   - name: apache Installation
     yum: pkg=httpd state=latest

   - name: Copying configuration file to conf directory of apache
     copy:
       src: /templates/httpd.j2
       dest: /etc/httpd/conf/httpd.conf

   - name: (Enable it on System Boot)
     service: name=httpd enabled=yes
     notify:
       - start apache
   - name: adding group "tomcat"
     group: name=tomcat

   - name: adding user "tomcat" to group "tomcat"
     user: name=tomcat group=tomcat home=/usr/share/tomcat createhome=no
     become: True
     become_method: sudo

   - name: Downloading Tomcat 7
     get_url: url=http://archive.apache.org/dist/tomcat/tomcat-7/v7.0.61/bin/apache-tomcat-7.0.61.tar.gz dest=/opt/apache-tomcat-7.0.61.tar.gz

   - name: Extracting archive apache-tomcat-7.0.61.tar.gz
     command: chdir=/usr/share /bin/tar xvf /opt/apache-tomcat-7.0.61.tar.gz -C /opt/ creates=/opt/apache-tomcat-7.0.61

   - name: creating Symlink of tomcat to /usr/share/tomcat
     file: src=/opt/apache-tomcat-7.0.61 path=/usr/share/tomcat state=link

   - name: Changing ownership of Tomcat installation
     file: path=/usr/share/tomcat/ owner=tomcat group=tomcat state=directory recurse=yes

   - name: Configure Tomcat user
     template: src=/opt/tomcat/tomcat-users.xml dest=/usr/share/tomcat/conf/
     notify: restart tomcat

   - name: Copying Jenkins war file to webapps of tomcat
     copy:
       src: /opt/jenkins/jenkins.war
       dest: /usr/share/tomcat/webapps/
       owner: tomcat
       group: tomcat

   - name: Execute the script to stop tomcat
     command: su - tomcat -c "/usr/share/tomcat/bin/shutdown.sh"

   - name: Execute the script
     command: su - tomcat -c "/usr/share/tomcat/bin/startup.sh"

   - name: Jenkins Admin password
     command: cat /usr/share/tomcat/.jenkins/secrets/initialAdminPassword
     changed_when: false
     register: pass

